server:
  port: 80

spring:
  application:
    name: Blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

